export type Guide = {
  id: string;
  name: string;
  photo: string;
  badge: "Govt. Approved" | "Verified Local" | "Safety Certified" | "Community Volunteer";
  languages: string[];
  specialty: string;
  rating: number;
  reviewsCount: number;
  hourlyRate: number;
  phone: string;
  whatsapp: string;
  available: boolean;
  availabilityText: string;
  bio: string;
  experienceYears: number;
  isVolunteer?: boolean;
  chatReplies?: string[];
  credentials: {
    licenseNo: string;
    backgroundChecked: boolean;
    firstAidCertified: boolean;
    policeVerified: boolean;
  };
  areasCovered: string[];
};

export const localGuides: Guide[] = [
  {
    id: "guide-rajesh",
    name: "Rajesh Sharma",
    photo: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=800&auto=format&fit=crop",
    badge: "Govt. Approved",
    languages: ["English", "Hindi", "French"],
    specialty: "Fort Architecture & Royal History",
    rating: 4.9,
    reviewsCount: 142,
    hourlyRate: 600,
    phone: "+919829012345",
    whatsapp: "919829012345",
    available: true,
    availabilityText: "Available Now",
    bio: "Certified official Rajasthan Tourism guide with 12+ years sharing the deep architectural secrets and untold legends of Amber Fort and City Palace.",
    experienceYears: 12,
    credentials: {
      licenseNo: "RJ-TOU-2024-8831",
      backgroundChecked: true,
      firstAidCertified: true,
      policeVerified: true,
    },
    areasCovered: ["Amer Fort", "Jaigarh", "Nahargarh", "City Palace"],
  },
  {
    id: "guide-sunita",
    name: "Sunita Meena",
    photo: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=800&auto=format&fit=crop",
    badge: "Verified Local",
    languages: ["English", "Hindi", "Marwari"],
    specialty: "Hidden Stepwells & Artisan Crafts",
    rating: 5.0,
    reviewsCount: 98,
    hourlyRate: 450,
    phone: "+919829067890",
    whatsapp: "919829067890",
    available: true,
    availabilityText: "Available Now",
    bio: "Born in Amer village. Sunita leads gentle, unhurried cultural walks focusing on block printing havelis, stepwell geometry, and quiet temple squares.",
    experienceYears: 7,
    credentials: {
      licenseNo: "RJ-TOU-2023-4109",
      backgroundChecked: true,
      firstAidCertified: false,
      policeVerified: true,
    },
    areasCovered: ["Panna Meena", "Amer Village", "Anokhi Museum", "Gaitore"],
  },
  {
    id: "guide-vikram",
    name: "Vikram Rathore",
    photo: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=800&auto=format&fit=crop",
    badge: "Safety Certified",
    languages: ["English", "Hindi", "German"],
    specialty: "Safe After Dark Escort & Night Food",
    rating: 4.8,
    reviewsCount: 84,
    hourlyRate: 550,
    phone: "+919829045678",
    whatsapp: "919829045678",
    available: true,
    availabilityText: "Available Now",
    bio: "Former defense serviceman and certified tourism safety escort. Specializes in lit evening bazaar exploration, street food trails, and solo traveler safety.",
    experienceYears: 9,
    credentials: {
      licenseNo: "RJ-SEC-2022-1980",
      backgroundChecked: true,
      firstAidCertified: true,
      policeVerified: true,
    },
    areasCovered: ["Old City Bazaars", "Ramganj", "Jal Mahal Promenade", "MI Road"],
  },
  {
    id: "guide-aisha",
    name: "Aisha Qureshi",
    photo: "https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?q=80&w=800&auto=format&fit=crop",
    badge: "Govt. Approved",
    languages: ["English", "Hindi", "Urdu"],
    specialty: "Authentic Culinary & Spice Routes",
    rating: 4.9,
    reviewsCount: 116,
    hourlyRate: 500,
    phone: "+919829023456",
    whatsapp: "919829023456",
    available: false,
    availabilityText: "Available Tomorrow 9 AM",
    bio: "Food writer and heritage culinary storyteller. Takes travelers inside historic sweet houses, family-run kachori stalls, and spice grinding lanes of Walled City.",
    experienceYears: 8,
    credentials: {
      licenseNo: "RJ-TOU-2024-2210",
      backgroundChecked: true,
      firstAidCertified: true,
      policeVerified: true,
    },
    areasCovered: ["Johari Bazaar", "Tripolia", "Chandpole", "LMB Lane"],
  },
  {
    id: "guide-manvendra",
    name: "Manvendra Singh",
    photo: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=800&auto=format&fit=crop",
    badge: "Verified Local",
    languages: ["English", "Hindi"],
    specialty: "Aravali Ridge & Wildlife Photography",
    rating: 4.8,
    reviewsCount: 62,
    hourlyRate: 650,
    phone: "+919829098765",
    whatsapp: "919829098765",
    available: true,
    availabilityText: "Available Now",
    bio: "Naturalist and heritage photographer guiding scenic sunrise loops along the ancient Aravali watchtowers and water harvesting check-dams.",
    experienceYears: 6,
    credentials: {
      licenseNo: "RJ-ECO-2023-7740",
      backgroundChecked: true,
      firstAidCertified: true,
      policeVerified: true,
    },
    areasCovered: ["Nahargarh Forest", "Hathni Kund", "Sagar Lake", "Jaigarh Walls"],
  },
];

export const communityVolunteers: Guide[] = [
  {
    id: "vol-arjun",
    name: "Arjun Balwani",
    photo: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?q=80&w=800&auto=format&fit=crop",
    badge: "Community Volunteer",
    languages: ["English", "Hindi", "Rajasthani"],
    specialty: "Heritage Stepwells & Quiet Corners",
    rating: 4.7,
    reviewsCount: 34,
    hourlyRate: 0,
    phone: "+919876001001",
    whatsapp: "919876001001",
    available: true,
    availabilityText: "Online · Ready to Chat",
    bio: "3rd-year architecture student at Jaipur University. I've mapped every baoli (stepwell) within 15 km of Amer Fort. Ask me about Panna Meena's hidden sunrise angle or Naulakha stepwell on the outskirts!",
    experienceYears: 2,
    isVolunteer: true,
    chatReplies: [
      "Hey! Great to hear from you 😊 Which area are you exploring today?",
      "Oh Panna Meena is stunning! Best time is 7–9 AM when the light hits the geometric stairs. Avoid weekends if you can.",
      "For getting there, take a shared auto from Amer bus stand — about ₹20. The stepwell entry is free!",
      "Happy to help anytime. Safe travels! 🙏",
    ],
    credentials: {
      licenseNo: "VOL-COMM-2025-001",
      backgroundChecked: true,
      firstAidCertified: false,
      policeVerified: false,
    },
    areasCovered: ["Panna Meena", "Amer Village", "Ghat Ki Guni", "Naulakha Stepwell"],
  },
  {
    id: "vol-priya",
    name: "Priya Joshi",
    photo: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?q=80&w=800&auto=format&fit=crop",
    badge: "Community Volunteer",
    languages: ["English", "Hindi", "Gujarati"],
    specialty: "Street Food & Local Market Secrets",
    rating: 4.9,
    reviewsCount: 56,
    hourlyRate: 0,
    phone: "+919876002002",
    whatsapp: "919876002002",
    available: true,
    availabilityText: "Online · Ready to Chat",
    bio: "Born and raised near Johari Bazaar. I'll tell you exactly which kachori stall is fried fresh at 8 AM, where the best thali is under ₹150, and which lanes are safe for solo women at night.",
    experienceYears: 3,
    isVolunteer: true,
    chatReplies: [
      "Namaste! I'm Priya, your local foodie guide 🌶 Where are you headed?",
      "If you're near Johari Bazaar, go to Rawat Mishthan Bhandar for kachori — opens at 7:30 AM and sells out by 10!",
      "LMB is also excellent but pricier. For budget thali under ₹120, try the lane behind Tripolia Gate.",
      "DM me whenever! I check messages every hour. Enjoy Jaipur's flavors! 🍛",
    ],
    credentials: {
      licenseNo: "VOL-COMM-2025-002",
      backgroundChecked: true,
      firstAidCertified: false,
      policeVerified: false,
    },
    areasCovered: ["Johari Bazaar", "Tripolia Gate", "LMB Lane", "Ramganj Market"],
  },
  {
    id: "vol-ravi",
    name: "Ravi Kumar Nath",
    photo: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?q=80&w=800&auto=format&fit=crop",
    badge: "Community Volunteer",
    languages: ["English", "Hindi"],
    specialty: "Photography Spots & Rooftop Views",
    rating: 4.8,
    reviewsCount: 41,
    hourlyRate: 0,
    phone: "+919876003003",
    whatsapp: "919876003003",
    available: false,
    availabilityText: "Back Online at 6 PM",
    bio: "Amateur photographer and Jaipur resident for 24 years. I know every rooftop, every angle, and the exact 40-minute golden hour window. Currently a media student at MDS University, Ajmer.",
    experienceYears: 4,
    isVolunteer: true,
    chatReplies: [
      "Hey! Ravi here 📷 What kind of shots are you looking for — architecture, people, or landscapes?",
      "For Amber Fort, position yourself at the lake reflection point on Amer Road at 7:15 AM for the best shot.",
      "Nahargarh sunset from the third parapet is pure gold between 6:10–6:40 PM. Bring a wide lens!",
      "I'll be online by 6 PM if you want more tips. Drop me your travel dates!",
    ],
    credentials: {
      licenseNo: "VOL-COMM-2025-003",
      backgroundChecked: true,
      firstAidCertified: false,
      policeVerified: false,
    },
    areasCovered: ["Nahargarh Viewpoint", "Amber Fort Lake", "Hawa Mahal Rooftops", "Jaigarh Walls"],
  },
  {
    id: "vol-fatima",
    name: "Fatima Siddiqui",
    photo: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=800&auto=format&fit=crop",
    badge: "Community Volunteer",
    languages: ["English", "Hindi", "Urdu"],
    specialty: "Women Traveler Safety & Old City Navigation",
    rating: 5.0,
    reviewsCount: 29,
    hourlyRate: 0,
    phone: "+919876004004",
    whatsapp: "919876004004",
    available: true,
    availabilityText: "Online · Ready to Chat",
    bio: "Law student and women's rights advocate. I help solo women travelers navigate Jaipur's Old City safely — including which lanes to avoid at night, which autos are reliable, and where the women's helpdesk is.",
    experienceYears: 2,
    isVolunteer: true,
    chatReplies: [
      "Hi! Fatima here 👋 Are you traveling solo? I can give you a tailored safety rundown for Old City.",
      "For the bazaar area: stick to the main Johari Bazaar road after 8 PM. The lanes behind it get deserted.",
      "Prepaid pink autos (operated by women) are safe and have GPS. Find the stand near Badi Chaupar.",
      "Women's helpline is 1091 — save it now. And feel free to message me anytime you feel unsure! 💙",
    ],
    credentials: {
      licenseNo: "VOL-COMM-2025-004",
      backgroundChecked: true,
      firstAidCertified: false,
      policeVerified: false,
    },
    areasCovered: ["Old City Walled Area", "Badi Chaupar", "Johari Bazaar", "Chandpole"],
  },
  {
    id: "vol-deepak",
    name: "Deepak Choudhary",
    photo: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?q=80&w=800&auto=format&fit=crop",
    badge: "Community Volunteer",
    languages: ["English", "Hindi", "Marwari"],
    specialty: "Hidden Gems & Off-the-Beaten-Path Jaipur",
    rating: 4.8,
    reviewsCount: 48,
    hourlyRate: 0,
    phone: "+919876005005",
    whatsapp: "919876005005",
    available: true,
    availabilityText: "Online · Ready to Chat",
    bio: "Auto-rickshaw driver turned amateur historian. I've driven 11 years in Jaipur and discovered places most guides have never seen — Gaitore cenotaphs at dawn, Sagar Lake at dusk, the secret artisan workshops of Nataniiyoon.",
    experienceYears: 5,
    isVolunteer: true,
    chatReplies: [
      "Kem cho! Deepak here. Want to skip the tourist circuit and see the REAL Jaipur?",
      "Gaitore Ki Chhatriyan at 6:30 AM — you'll have the entire royal cenotaph complex to yourself. Absolutely zero crowds!",
      "Sagar Lake behind Amer Fort has a secret trail. I can tell you the exact path that most drivers don't know.",
      "Message me your hotel location and I'll plan a 3-hour hidden Jaipur loop for you. Free of charge! 🛺",
    ],
    credentials: {
      licenseNo: "VOL-COMM-2025-005",
      backgroundChecked: true,
      firstAidCertified: false,
      policeVerified: false,
    },
    areasCovered: ["Gaitore Ki Chhatriyan", "Sagar Lake", "Sisodia Bagh", "Nataniiyoon Ki Haveli"],
  },
];
